### ISSUE TITLE
cloned but not working

### ISSUE THREAD

**Issue by Pandurangbhor** [Autodesk-Forge/forge-revit.ifc.scheduler#1]
showing npm install error

**Comment by yiskang** [comment]
Hi @Pandurangbhor, could you share the error message you saw with me?

**Comment by Pandurangbhor** [comment]
Can you provide a video that showing process of installation from clone the project.If there are any purchases like npm. I think it should work free of cost. am i right or wrong?

**Comment by yiskang** [comment]
Here you go: https://youtu.be/0lrctnbBbPY

This sample uses paid API [Model Derivative API](https://aps.autodesk.com/en/docs/model-derivative/v2/reference/http/en/docs/model-derivative/v2/reference/http/job-POST) to translate RVT to IFC. So, your statement "I think it should work free of cost." is incorrect.
